Citizen.CreateThread(function()
    AddTextEntry("is350","Lexus IS350")
    AddTextEntry("lb750sv","Lamborghini 750SV")
    AddTextEntry("dbx","Aston Martin DBX")
    AddTextEntry("bnrpandem","Nissan GTR R32 Pandem")
    AddTextEntry("m5f90","BMW M5 F90")
    AddTextEntry("majsr","Nissan GTR R32")
    AddTextEntry("rx7ac","Mazda RX7")
    AddTextEntry("a80","Toyota Supra MK4")
    AddTextEntry("m190e","Mercedes Benz 190E")
    AddTextEntry("models","Tesla Model S")
    AddTextEntry("dmvcamry","DMV Toyota Camry")
    AddTextEntry("bentayga17","Bentley Bentayga")
    AddTextEntry("schwarzer2","Benefactor Schwarter6str")
    AddTextEntry("19ramoffroad", "2019 Dodge Ram Off-Road")
    AddTextEntry("rx8r", "Mazda RX-8 Spirit R")
    AddTextEntry("16charger", "Dodge Charger 2016")
    AddTextEntry("chr20", "Dodge Charger 2016 Hellcat")
    AddTextEntry("paragonxr", "Enus Paragon XR")
    AddTextEntry("rs62", "Audi RS6 Advant")
    AddTextEntry("lwhuracan", "Lamborghini Huracan LP610-4 LW")
    AddTextEntry("rm3e36d", "BMW E36 Drift")
    AddTextEntry("demon", "Dodge Demon")
    AddTextEntry("r31", "Nissan Skyline R31")
    AddTextEntry("nis13", "Nissan Silvia S13")
    AddTextEntry("fleet78low", "Cadillac Fleetwood Brougham D'elegance")
    AddTextEntry("a6", "Audi A6 Quattro")
    AddTextEntry("zr3806str", "Annis ZR-380 Custom")
    AddTextEntry("tampa4", "Declasse Drift Tampa Custom")
    AddTextEntry("filthynsx", "Acura NSX Liberty Walk")
    AddTextEntry("ram2500j", "Dodge Ram 2500")
    AddTextEntry("c63w205", "Mercedes C63 AMG")
    AddTextEntry("gtr32rbnormal", "Nissan Skyline R32 Rocket Bunny")
    AddTextEntry("pistas", "Ferrari 488 Pista Spider")
    AddTextEntry("shelbygt500w", "Shelby Mustang GT500 Widebody")
    AddTextEntry("m5e60", "BMW M5 E60")
    AddTextEntry("kev", "Cadillac CTS-V 2012")
    AddTextEntry("m4lb", "BMW M4 Liberty Walk Drift Edition")
    AddTextEntry("bmwm8", "BMW M8")
    AddTextEntry("v250", "Mercedes V-Class 250 LWB")
end)