function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
	AddTextEntry('Ford', 'Ford')
	AddTextEntry('Dodge' , 'Dodge')
	AddTextEntry('NISSAN', 'Nissan')
	AddTextEntry('Chevy', 'Chevrolet')
	AddTextEntry('Honda', 'Honda')
	AddTextEntry('SUBARU', 'Subaru')
	AddTextEntry('Mercedes', 'Mercedes-Benz')
	AddTextEntry('BUGATTI', 'Bugatti')
	AddTextEntry('BMW', 'BMW')
	AddTextEntry('Cadillac', 'Cadillac')
	AddTextEntry('Mitsubishi', 'Mitsubishi')
	AddTextEntry('lambo', 'Lamborghini')
	AddTextEntry('Koenigsegg', 'Koenigsegg')
	AddTextEntry('AUDI', 'Audi')
	AddTextEntry('Porsche', 'Porsche')
	
	AddTextEntry('10ram', '2010 Ram 3500')
	AddTextEntry('ninjah2', 'Kawasaki Ninja H2/H2R')
	AddTextEntry('r35', 'GTR (R35)')
	AddTextEntry('19ram', '2019 Ram 1500')
	AddTextEntry('LADYBIRD', 'Ladybird')
	AddTextEntry('CLS63', 'CLS 6.3')
	AddTextEntry('RAID', 'Challenger Raid')
	AddTextEntry('DIVO', '2019 Divo')
	AddTextEntry('rmodm4gts', 'M4 GTS')
	AddTextEntry('CHIRON17', '2017 Chiron')
	AddTextEntry('SSTI', '2004 WRX STI')
	AddTextEntry('CTSV16', '2016 CTS-V')
	AddTextEntry('evovaris', '2019 Lancer Evo X VARIS')
	AddTextEntry('Terzo', '2018 Terzo Millennio')
	AddTextEntry('jes', '2020 Jesko')
	AddTextEntry('rmodrs7', 'RS7 Sportback Widebody')
	AddTextEntry('brz13', "BRZ '13")
	AddTextEntry('GREDDY', 'Greddy')
	AddTextEntry('INGS', 'Ings')
	AddTextEntry('GARGE', 'Garge Vary')
	AddTextEntry('DELETES', 'Spoiler Delete')
	AddTextEntry('NOHOOD', 'No Hood')
	AddTextEntry('CWEST', 'C-West')
	AddTextEntry('RBKIT', 'Rocket Bunny')
	AddTextEntry('RACEWING', 'Race Wing')
	AddTextEntry('RMAGIC', 'R-Magic')
	AddTextEntry('918SPYDER', '2015 918 Spyder')
	AddTextEntry("CESC21", "'21 Escalade")


end)