----------------------------------------------------------------
-- Copyright © 2019 by Guy Shefer
-- Made By: Guy293
-- GitHub: https://github.com/Guy293
-- Fivem Forum: https://forum.fivem.net/u/guy293/
----------------------------------------------------------------
Config 				  = {}
Config.UseGENCore 		  = true
Config.CooldownPolice = 700 -- Will work with GENCore only
Config.cooldown		  = 1400

-- Add/remove weapon hashes here to be added for holster checks.
Config.Weapons = {
	
	"WEAPON_KNIFE",
	"WEAPON_NIGHTSTICK",
	"WEAPON_HAMMER",
	"WEAPON_BAT",
	"WEAPON_GOLFCLUB",
	"WEAPON_CROWBAR",
	"WEAPON_BOTTLE",
	"WEAPON_DAGGER",
	"WEAPON_HATCHET",
	"WEAPON_MACHETE",
	"WEAPON_BATTLEAXE",
	"WEAPON_POOLCUE",
	"WEAPON_WRENCH",

	'WEAPON_PISTOL',
	'WEAPON_PISTOL_MK2',
	'WEAPON_DOUBLEACTION',
	'WEAPON_COMBATPISTOL',	
	'WEAPON_APPISTOL',	 
	'WEAPON_PISTOL50', 
	'WEAPON_VINTAGEPISTOL',
	'WEAPON_HEAVYPISTOL',
	'WEAPON_SNSPISTOL',
	'WEAPON_SNSPISTOL_MK2', 
	'WEAPON_FLAREGUN',
	'WEAPON_MARKSMANPISTOL',
	'WEAPON_REVOLVER',
	'WEAPON_REVOLVER_MK2',
	'WEAPON_STUNGUN',

	'WEAPON_MICROSMG',
	'WEAPON_SMG',			 
	'WEAPON_MG',				 
	'WEAPON_COMBATMG',
	'WEAPON_GUSENBERG',
	'WEAPON_COMBATPDW', 		
	'WEAPON_MACHINEPISTOL', 	 
	'WEAPON_ASSAULTSMG', 		 
	'WEAPON_MINISMG', 			 

	'WEAPON_ASSAULTRIFLE', 
	'WEAPON_ASSAULTRIFLE_MK2',
	'WEAPON_CARBINERIFLE',
	'WEAPON_CARBINERIFLE_MK2', 	 
	'WEAPON_ADVANCEDRIFLE', 	 
	'WEAPON_SPECIALCARBINE',
	'WEAPON_SPECIALCARBINE_MK2',
	'WEAPON_BULLPUPRIFLE', 		 
	'WEAPON_COMPACTRIFLE', 		 

	'WEAPON_PUMPSHOTGUN',
	'WEAPON_PUMPSHOTGUN_MK2', 		 
	'WEAPON_SAWNOFFSHOTGUN', 	
	'WEAPON_BULLPUPSHOTGUN', 	 
	'WEAPON_ASSAULTSHOTGUN', 	 
	'WEAPON_MUSKET', 			 
	'WEAPON_HEAVYSHOTGUN', 		 
	'WEAPON_DBSHOTGUN', 		 
	'WEAPON_AUTOSHOTGUN', 		 

	'WEAPON_SNIPERRIFLE', 		 
	'WEAPON_HEAVYSNIPER', 		 
	'WEAPON_MARKSMANRIFLE', 	

	'WEAPON_REMOTESNIPER', 		 
	'WEAPON_STINGER', 			 

	'WEAPON_GRENADELAUNCHER', 	 
	'WEAPON_RPG', 				 
	'WEAPON_MINIGUN', 			 
	'WEAPON_FIREWORK', 			 
	'WEAPON_RAILGUN', 			 
	'WEAPON_HOMINGLAUNCHER', 	 
	'WEAPON_COMPACTLAUNCHER', 	 

	'WEAPON_STICKYBOMB', 		 
	'WEAPON_MOLOTOV', 			 
	'WEAPON_FIREEXTINGUISHER', 	 
	'WEAPON_PETROLCAN', 		 
	'WEAPON_PROXMINE', 			 
	'WEAPON_SNOWBALL', 			 
	'WEAPON_BALL', 				
	'WEAPON_GRENADE', 			 
	'WEAPON_SMOKEGRENADE', 		
	'WEAPON_BZGAS', 			 

	'WEAPON_DIGISCANNER', 		 
	'WEAPON_DAGGER', 			 
	'WEAPON_GARBAGEBAG', 		
	'WEAPON_HANDCUFFS', 		
	'WEAPON_BATTLEAXE', 		 
	'WEAPON_PIPEBOMB', 			
	'WEAPON_POOLCUE', 			 
	'WEAPON_WRENCH', 			
	'GADGET_NIGHTVISION', 		
	'GADGET_PARACHUTE',

}

Config.DisabedSupressor = {
	137902532, --WEAPON_VINTAGEPISTOL
}