--[[ function AddTextEntry(key, value)
    Citizen.InvokeNative(GetHashKey(ADD_TEXT_ENTRY), key, value)
end ]]

Citizen.CreateThread(function()
	Citizen.Wait(0)
    AddTextEntry('vic11', '2011 Ford Crown Victoria')
    AddTextEntry('taurus', '2016 Ford Taurus')
    AddTextEntry('charger', '2018 Dodge Charger')
    AddTextEntry('charger14', '2014 Dodge Charger')
    AddTextEntry('explorer', '2016 Ford Explorer')
    AddTextEntry('2015polstang', '2015 Ford Mustang GT500')
    AddTextEntry('ram2500', 'Dodge Ram')
    AddTextEntry('tahoe', '2020 Chevrolet Tahoe')
    AddTextEntry('tahe13', '2013 Chevrolet Tahoe DoC')
    AddTextEntry('policeb2', 'BF400 Police Off-Road Bike')
    AddTextEntry('as350', 'as350 eurocopter')
    AddTextEntry('dvdt3', 'Dominator GTX UC')
    AddTextEntry('FIBJackal', 'Jackal UC')
    AddTextEntry('policefelon', 'Felon UC')
    AddTextEntry('polschafter3', 'Schafter V12 UC')
    AddTextEntry('tailgater2', 'Tailgater UC')
    AddTextEntry('asea3', 'Asea UC')
    AddTextEntry('sspres', 'SWAT Suburban')
    AddTextEntry('nspeedo', 'Vapid Speedo Police Van')
    AddTextEntry('fibn', 'Pfister Neon UC')
end) 